const teamMemmbers = [
  {
    name: "Ilies",
    surname: "Guellaf",
    age: 21,
    city: "Los Montesinos",
    hobby: "Dibujar",
    favoriteFood: "Ensaladilla rusa",
    favoriteVideoGame: "Pokemon HeartGold",
    favoriteFilm: "Blade Runner 2049",
    favoriteBook: "Manga:PunPun",
    petName: "",
  },
  {
    name: "Wilmer",
    surname: "Salazar",
    age: 21,
    city: "Los Montesinos",
    hobby: "Dibujar",
    favoriteFood: "Ensaladilla rusa",
    favoriteVideoGame: "Pokemon HeartGold",
    favoriteFilm: "Blade Runner 2049",
    favoriteBook: "Manga:PunPun",
    petName: "",
  },
];